import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'All': 'All',
          'Vanchan': 'Vanchan',
          'Mala jap': 'Mala Jap',
          'Home': 'Home',
          'Language': 'Language',
          'Refer a friend': 'Refer a friend',
          'Rate Us': 'Rate Us',
          'Sign Out': 'Sign Out',
          'English': 'English',
          'Gujarati': 'Gujarati',
          'Cancel': 'Cancel',
          'Done': 'Done',
          'Search PDF by Name': 'Search PDF by Name',
          'Swaminarayan': ' Jai Shree Swaminarayan',
          'User data list': 'User data list',
          'Upload PDF': 'Upload PDF',
          'Select Language': 'Select Language',
          'No PDF found': 'No PDF found',
          'Go to MalaJap': 'Go to MalaJap',
          'Go to Vanchan': 'Go to Vanchan',
          'Welcome': 'Welcome',
          'Profile': 'Profile',
          'Credit Score:': 'Credit Score:',
          'PDF Description': 'PDF Description',
          'Click here to upload PDF Photo': 'Click here to upload PDF Photo',
          'Click here to upload PDF': 'Click here to upload PDF',
          'Select PDF language': 'Select PDF language',
          'Are you sure you want to sign out?': 'Are you sure you want to sign out?',
          'Yes': 'Yes',
          'No': 'No',
          'Last Month': 'Last Month',
          'Last Week': 'Last Week',
          'Date': 'Date',
          'Credits': 'Credits',
          'Mobile No': 'Mobile No',
          'Total Credits': 'Total Credits',
          'Village': 'Village',
        },
        'hi_IN': {
          'All': 'તમામ',
          'Vanchan': 'વાંચન',
          'Mala Jap': 'માલા જાપ',
          'Home': 'ઘર',
          'Language': 'ભાષા',
          'Refer a friend': 'મિત્ર નો સંદર્ભ લો',
          'Rate Us': 'રેટ કરો',
          'Sign Out': 'સાઇન આઉટ કરો',
          'English': 'અંગ્રેજી',
          'Gujarati': 'ગુજરાતી',
          'Cancel': 'રદ કરો',
          'Done': 'પસંદ કરો',
          'Search PDF by Name': 'નામ દ્વારા પીડીએફ શોધો',
          'Swaminarayan': ' જય શ્રી સ્વામિનારાયણ',
          'Select Language': 'ભાષા પસંદ કરો',
          'Upload PDF': 'પીડીએફ અપલોડ કરો',
          'User Data List': 'વપરાશકર્તા ડેટા સૂચિ',
          'No PDF found': 'કોઈ PDF મળી નથી',
          'Go to MalaJap': 'માલાજાપ પર જાઓ',
          'Go to Vanchan': 'વાંચન પર જાઓ',
          'Welcome': 'સુસ્વાગતમ્',
          'Profile': 'પ્રોફાઇલ',
          'Credit Score:': 'ક્રેડિટ સ્કોર',
          'PDF Description': 'પીડીએફ વર્ણન',
          'Select PDF language': 'પીડીએફ ની ભાષા પસંદ કરો ',
          'Click here to upload PDF Photo': 'પીડીએફ ફોટો અપલોડ કરવા માટે અહીં ક્લિક કરો ',
          'Click here to upload PDF': 'પીડીએફ અપલોડ કરવા માટે અહીં ક્લિક કરો',
          'Are you sure you want to sign out?': 'શું તમે ખરેખર સાઇન આઉટ કરવા માંગો છો? ',
          'Yes': 'હા',
          'No': 'ના',
          'Last Month': 'છેલ્લા મહિને',
          'Last Week': 'છેલ્લા સપ્તાહે',
          'Date': ' તારીખ',
          'Credits': 'ક્રેડિટ',
          'Mobile No': 'મોબાઇલ',
          'Total Credits': 'ક્રેડિટ',
          'Village': 'ગામ',
        }
      };
}
